#!/usr/bin/env node
// Publish the current MPW build on the dist branch and tag it mpw-plugin-v<version>.
//
//   node scripts/release_plugin.mjs            commit + tag locally
//   node scripts/release_plugin.mjs --push     also push the dist branch and the tag to origin
//
// Preconditions: clean working tree and HEAD tagged v<version> (the canonical release commit).
// After pushing, bump the marketplace pin in github.com/HeiTuz/heituz-plugins:
//   node scripts/bump.mjs mpw mpw-plugin-v<version>
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { buildPlugin, validatePlugin } from "./build_plugin.mjs";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const DIST_BRANCH = "dist";

function git(args, { cwd = root, allowFail = false } = {}) {
  const result = spawnSync("git", args, { cwd, encoding: "utf8" });
  if (result.status !== 0 && !allowFail) throw new Error("git " + args.join(" ") + " failed: " + (result.stderr || result.stdout));
  return result;
}

function main(argv = process.argv.slice(2)) {
  const push = argv.includes("--push");
  const unknown = argv.filter((arg) => arg !== "--push");
  if (unknown.length) throw new Error("unknown flag: " + unknown.join(" "));
  const version = JSON.parse(fs.readFileSync(path.join(root, "package.json"), "utf8")).version;
  const sourceTag = "v" + version;
  const distTag = "mpw-plugin-v" + version;
  if (git(["status", "--porcelain"]).stdout.trim()) throw new Error("working tree is not clean");
  const head = git(["rev-parse", "HEAD"]).stdout.trim();
  const tagged = git(["rev-parse", sourceTag + "^{commit}"], { allowFail: true });
  if (tagged.status !== 0 || tagged.stdout.trim() !== head) throw new Error("HEAD must be tagged " + sourceTag);
  if (git(["rev-parse", "-q", "--verify", "refs/tags/" + distTag], { allowFail: true }).status === 0) throw new Error(distTag + " already exists");

  if (push) git(["fetch", "origin", DIST_BRANCH], { allowFail: true });
  const worktree = fs.mkdtempSync(path.join(os.tmpdir(), "mpw-dist-"));
  const hasLocal = git(["rev-parse", "-q", "--verify", "refs/heads/" + DIST_BRANCH], { allowFail: true }).status === 0;
  const hasRemote = git(["rev-parse", "-q", "--verify", "refs/remotes/origin/" + DIST_BRANCH], { allowFail: true }).status === 0;
  try {
    if (hasLocal) git(["worktree", "add", worktree, DIST_BRANCH]);
    else if (hasRemote) git(["worktree", "add", "-b", DIST_BRANCH, worktree, "origin/" + DIST_BRANCH]);
    else {
      git(["worktree", "add", "--detach", worktree, head]);
      git(["checkout", "--orphan", DIST_BRANCH], { cwd: worktree });
      git(["rm", "-rfq", "."], { cwd: worktree });
    }
    for (const entry of fs.readdirSync(worktree)) {
      if (entry !== ".git") fs.rmSync(path.join(worktree, entry), { recursive: true, force: true });
    }
    const pluginDir = buildPlugin(worktree);
    const { files, problems } = validatePlugin(pluginDir);
    if (problems.length) throw new Error("plugin validation failed:\n  " + problems.join("\n  "));
    fs.writeFileSync(path.join(worktree, "README.md"), [
      "# MPW plugin distribution",
      "",
      "Generated by scripts/build_plugin.mjs from HeiTuz/MPW " + sourceTag + " (" + head + "). Do not edit this branch.",
      "",
      "Install through the HeiTuz marketplace: https://github.com/HeiTuz/heituz-plugins",
      "",
    ].join("\n"));
    git(["add", "-A"], { cwd: worktree });
    git(["commit", "-qm", "Release MPW plugin " + version + " from " + sourceTag + " (" + head.slice(0, 7) + ")"], { cwd: worktree });
    git(["tag", "-a", distTag, "-m", "MPW plugin " + version + " built from " + head], { cwd: worktree });
    const distHead = git(["rev-parse", "HEAD"], { cwd: worktree }).stdout.trim();
    if (push) {
      git(["push", "origin", DIST_BRANCH], { cwd: worktree });
      git(["push", "origin", "refs/tags/" + distTag], { cwd: worktree });
    }
    console.log(JSON.stringify({ version, source_commit: head, dist_commit: distHead, dist_tag: distTag, files, pushed: push }, null, 2));
  } finally {
    git(["worktree", "remove", "--force", worktree], { allowFail: true });
    fs.rmSync(worktree, { recursive: true, force: true });
  }
}

try {
  main();
} catch (error) {
  console.error("release_plugin: " + (error.message || error));
  process.exitCode = 1;
}
